### ISSUE TITLE
Pie Chart of results

### ISSUE THREAD

**Issue by terabyte** [DustinRobison/StoryPointPoker#15]
Just switched over from app.storypoint.poker - thank you for this fantastic tool!

I especially appreciate the configurable room names, I've been asking the other one to implement rooms with no ambiguous characters for like, over a year. (i.e. no capital i and lowercase L).

Pretty much the only feature I miss from the other one is after you reveal votes, they show a pie chart of the votes so you can see at a glance what value got the most votes. It seems like this might be easy to do?  Maybe if I get a chance I will take a stab at it. If I did, would you accept an MR?

Thanks!

**Comment by DustinRobison** [comment]
I am glad you like the site, i would happily accept a PR
This is a good idea.  I will see if can get around to adding it with Apex charts or something simple

**Comment by DustinRobison** [comment]
After putting a little more thought into this I am going to rewrite some of the backend history to enable a historical list when show and clear votes was pressed with pie charts below.

**Comment by DustinRobison** [comment]
I decided to keep it very simple instead of writing out a whole history: https://github.com/DustinRobison/StoryPointPoker/commit/2c13b27860614d534560df37efee947b1e98b2ac

Feel free to give feedback

**Comment by terabyte** [comment]
We just noticed this feature got implemented during our sprint planning this morning!  Thanks so much for implementing it! :heart:
