### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by terabyte** [DustinRobison/StoryPointPoker#16]
There is a "fork me on github" button but with no license specified, there is considerable uncertainty preventing people from easily forking and/or contributing to this project.

I'd recommend UNLICENSE or Apache2.0 if you want a corporate-friendly open source license, or GPLv3 if you want a strong copyleft license.

**Comment by DustinRobison** [comment]
Good point, I will add a license

**Comment by DustinRobison** [comment]
Thank you for the suggestion, here we are: https://github.com/DustinRobison/StoryPointPoker/blob/master/LICENSE.md
