### ISSUE TITLE
Participant Icons no longer update when people have added votes

### ISSUE THREAD

**Issue by codyaverett** [DustinRobison/StoryPointPoker#17]
Expected to see these icons update to a "voted" state as new votes come in.  
Regression from the previous version?

Looks like this until scores are revealed.
<img width="48" alt="image" src="https://github.com/DustinRobison/StoryPointPoker/assets/3270702/acc734a6-f2b7-4bf7-be9c-fbc5dd5d0618">

https://github.com/DustinRobison/StoryPointPoker/blob/master/src/components/room/room-users-list.tsx#L122-L127

**Comment by DustinRobison** [comment]
Thank you for letting me know! 
Updated: https://github.com/DustinRobison/StoryPointPoker/commit/3b84255b10daf57f44f2c9acf81a4638afbcc09c

**Comment by codyaverett** [comment]
Thank you @DustinRobison! 🥷
